modLoader = "javafml" #mandatory
loaderVersion = "[43,)"

license = "MIT"
[[mods]] #mandatory
modId = "toughcreate" #mandatory
version = "${file.jarVersion}" #mandatory
displayName = "Tough Create" #mandatory
credits = "Thanks for this example mod goes to Java" #optional
authors = "DargonBoi" #optional
description = '''
Tuff Create
'''
# A dependency - use the . to indicate dependency for a specific modid. Dependencies are optional.
[[dependencies.toughcreate]] #optional
modId = "forge" #mandatory
mandatory = true #mandatory
versionRange = "[43,)" #mandatory
ordering = "NONE"
side = "BOTH"
# Here's another dependency
[[dependencies.toughcreate]]
modId = "minecraft"
mandatory = true
versionRange = "[1.19.2, 1.20)"
ordering = "NONE"
side = "BOTH"
[[dependencies.toughcreate]]
modId = "create"
mandatory = true
versionRange = "[v0.5.0i,)"
ordering = "AFTER"
side = "BOTH"
   
